### ISSUE TITLE
Too few arguments to function App\Mail\AdminEmail::__construct(), 1 passed and exactly 3 expected

### ISSUE THREAD

**Issue by jornwildenbeest** [Qoraiche/laravel-mail-editor#209]
## Describe the bug
When trying to access /maileclipse/mailables i get the following error:

```
Too few arguments to function App\Mail\AdminEmail::__construct(), 1 passed and exactly 3 expected
```

Stack tace:

```
[2022-06-21 08:59:52] local.ERROR: Too few arguments to function App\Mail\AdminEmail::__construct(), 1 passed and exactly 3 expected {"userId":2,"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function App\\Mail\\AdminEmail::__construct(), 1 passed and exactly 3 expected at /Users/jorn/Sites/**/app/Mail/AdminEmail.php:26)
[stacktrace]
#0 [internal function]: App\\Mail\\AdminEmail->__construct(Object(App\\Submission))
#1 /Users/jorn/Sites/**/vendor/qoraiche/laravel-mail-editor/src/MailEclipse.php(633): ReflectionClass->newInstanceArgs(Array)
#2 /Users/jorn/Sites/**/vendor/qoraiche/laravel-mail-editor/src/MailEclipse.php(806): Qoraiche\\MailEclipse\\MailEclipse::handleMailableViewDataArgs('App\\\\Mail\\\\AdminE...')
#3 /Users/jorn/Sites/**/vendor/qoraiche/laravel-mail-editor/src/MailEclipse.php(505): Qoraiche\\MailEclipse\\MailEclipse::buildMailable('App\\\\Mail\\\\AdminE...')
#4 /Users/jorn/Sites/**/vendor/qoraiche/laravel-mail-editor/src/MailEclipse.php(57): Qoraiche\\MailEclipse\\MailEclipse::mailablesList()
#5 /Users/jorn/Sites/**/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Qoraiche\\MailEclipse\\MailEclipse::getMailables()
#6 /Users/jorn/Sites/**/vendor/qoraiche/laravel-mail-editor/src/Http/Controllers/MailablesController.php(28): Illuminate\\Support\\Facades\\Facade::__callStatic('getMailables', Array)
#7 /Users/jorn/Sites/**/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Qoraiche\\MailEclipse\\Http\\Controllers\\MailablesController->index()
#8 /Users/jorn/Sites/**/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#9 /Users/jorn/Sites/**/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Qoraiche\\MailEclipse\\Http\\Controllers\\MailablesController), 'index')
#10 /Users/jorn/Sites/**/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#11 /Users/jorn/Sites/**/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
```

The mail class I am using:

```
<?php

namespace App\Mail;

use App\Submission;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class AdminEmail extends Mailable
{
    use Queueable, SerializesModels;

    public $submission;
    public $config;
    public $locale;


    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct(Submission $submission, array $config, String $locale)
    {
        $this->submission = $submission;
        $this->config = $config;
        $this->locale = $locale;
    }

```

## Laravel Version: 
v9.17.0

## MailEclipse package version: 
v4.0.3

## PHP version:
v8.0.19

**Comment by ReeceM** [comment]
Hi @jornwildenbeest, was this closed in favour of the other issue?

Or was this one resolved?

**Comment by jornwildenbeest** [comment]
Hi @ReeceM, this one was resolved.

I believe it had something to do with some old mail classes that had some old classes in the constructor method, without a factory and hasFactory trait etc..

I remembered I had this before and asked about in issue https://github.com/Qoraiche/laravel-mail-editor/issues/153,

Once I followed the steps exaplained there it started working again.

**Comment by ReeceM** [comment]
Awesome, I'll have a look into the other one opened in a little bit 👍
